---
- name: Loop - Create Multiple Files
  hosts: node1
  become: yes

  tasks:
    - name: Create multiple files
      file:
        path: "/opt/{{ item }}"
        state: touch
      loop:
        - file1.txt
        - file2.txt
        - file3.txt

