- name: Install Apache and start service
  hosts: node1
  become: yes   # use for 'sudo'
  vars:
    http_port: 80  # Define a variable
  tasks:
    - name: Install httpd package
      dnf:
        name: httpd
        state: present

    - name: Start and enable service
      service:
        name: httpd
        state: started
        enabled: true

